version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch
      
    working_directory: ~/cloud-devops-capstone
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            make setup
            source ~/.cloud-devops-capstone/bin/activate
            make install
            
      - save_cache:
          paths:
            - ./cloud-devops-capstone
          key: v1-dependencies-{{ checksum "requirements.txt" }}
            
      - run:
          name: run lint
          command: |
            source ~/.cloud-devops-capstone/bin/activate
            make lint
            
      - run:
          name: security scan
          command: |
            safety check

workflows:
  cicd-pipeline:
    jobs:
      - build
